/**
 * @dicsussion/zk — Groth16 Prover
 *
 * Wraps SnarkJS around the `rln_range_unified` circuit, implementing the
 * RFC 004 §5.1 `IZekPocBinding` surface.
 *
 * One proof simultaneously establishes membership, reputation tier, and
 * rate-limit compliance (RFC 003 §3.4) — merging them halves prover time
 * versus two separate proofs and keeps the wire envelope small.
 *
 * Proving is expensive (~1s on desktop WASM) and blocks its thread, so
 * production callers should drive this through `ProofWorkerPool` rather
 * than calling it inline.
 */

import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import { assertCanonicalField } from '../crypto/field.js';
import { TREE_DEPTH } from '../crdt/sparse-merkle-tree.js';
import type { MerkleProof } from '../crdt/sparse-merkle-tree.js';

/** Everything the circuit needs to produce a proof. */
export interface ProofInput {
  /** Private: the RLN identity secret a_0. */
  readonly identitySecret: bigint;
  /** Private: per-identity trapdoor. */
  readonly trapdoor: bigint;
  /** Private: actual reputation, proven ≥ threshold but never revealed. */
  readonly userScore: number;
  /** Private: inclusion path for this identity's commitment. */
  readonly merkleProof: MerkleProof;
  /**
   * Public: the **raw** tree root the inclusion path verifies against.
   *
   * Not `BoundedMembershipTree.root()`, which is version-bound — use
   * `rawRoot()`. The version binding wraps the tree rather than being
   * part of it, so the in-circuit Merkle gadget sees the unwrapped root.
   */
  readonly merkleRoot: bigint;
  /** Public: claimed tier threshold (0, 50, 100, 200). */
  readonly tierThreshold: number;
  readonly epoch: number;
  readonly messageIndex: number;
  /** Public: message commitment x. */
  readonly messageCommitment: bigint;
  /** Public: rolling-window quota for the claimed tier. */
  readonly quota: number;
}

/** A generated proof and its public signals. */
export interface ProofOutput {
  /** Groth16 proof object. */
  readonly proof: unknown;
  /** Raw public signals, outputs first. */
  readonly publicSignals: readonly string[];
  /** Rate-limiting nullifier η (circuit output 0). */
  readonly nullifier: bigint;
  /** Polynomial share y (circuit output 1). */
  readonly share: bigint;
  readonly epoch: number;
  readonly messageIndex: number;
}

/** Filesystem locations of the compiled circuit artifacts. */
export interface ProverArtifacts {
  /** `rln_range_unified.wasm` witness generator. */
  readonly wasmPath: string;
  /** `rln_final.zkey` proving key. */
  readonly zkeyPath: string;
  /** `verification_key.json`. */
  readonly verificationKeyPath: string;
}

/**
 * Convert a `ProofInput` into the flat signal map Circom expects.
 *
 * Path indices are the little-endian bits of the leaf index, matching
 * the traversal order in `sparse-merkle-tree.ts`.
 */
export function toCircuitSignals(input: ProofInput): Record<string, string | string[]> {
  assertCanonicalField(input.identitySecret);
  assertCanonicalField(input.trapdoor);
  assertCanonicalField(input.messageCommitment);
  assertCanonicalField(input.merkleRoot);

  if (input.merkleProof.siblings.length !== TREE_DEPTH) {
    throw new Error(
      `Merkle proof must have ${TREE_DEPTH} siblings, got ${input.merkleProof.siblings.length}`,
    );
  }
  if (input.userScore < input.tierThreshold) {
    // The circuit would reject this anyway; failing here gives a clear
    // error instead of an opaque witness-generation failure.
    throw new Error(
      `Cannot prove tier ${input.tierThreshold} with a score of ${input.userScore}`,
    );
  }
  if (input.messageIndex >= input.quota) {
    throw new Error(
      `Message index ${input.messageIndex} exceeds quota ${input.quota}`,
    );
  }

  return {
    identitySecret: input.identitySecret.toString(),
    trapdoor: input.trapdoor.toString(),
    userScore: String(input.userScore),
    pathElements: input.merkleProof.siblings.map(String),
    pathIndices: Array.from({ length: TREE_DEPTH }, (_, i) =>
      String((input.merkleProof.index >> i) & 1),
    ),
    merkleRoot: input.merkleRoot.toString(),
    tierThreshold: String(input.tierThreshold),
    epoch: String(input.epoch),
    messageIndex: String(input.messageIndex),
    messageCommitment: input.messageCommitment.toString(),
    quota: String(input.quota),
  };
}

/** Marker file identifying a single-party development ceremony. */
export const DEV_CEREMONY_MARKER = 'DEVELOPMENT_ONLY.md';

/**
 * Whether the artifacts alongside a key came from a development ceremony.
 *
 * A dev key is generated by one party who knows all the entropy, so it
 * can forge any claim the circuit makes. Detecting it is what lets
 * release tooling refuse to package it (RFC 003 §11.4).
 *
 * @param zkeyPath Path to the proving key.
 */
export function isDevelopmentCeremony(zkeyPath: string): boolean {
  return existsSync(join(dirname(zkeyPath), DEV_CEREMONY_MARKER));
}

/**
 * Groth16 prover over the unified RLN + range circuit.
 */
export class ZekPocProver {
  private verificationKey: unknown | null = null;
  private healthy = true;

  constructor(private readonly artifacts: ProverArtifacts) {}

  /**
   * Whether this prover is using development-only artifacts.
   *
   * Callers building a release MUST refuse to proceed when true.
   */
  get usesDevelopmentCeremony(): boolean {
    return isDevelopmentCeremony(this.artifacts.zkeyPath);
  }

  /** Whether the prover has not encountered an unrecoverable error. */
  isHealthy(): boolean {
    return this.healthy;
  }

  /** Clear cached state so the next call reloads artifacts. */
  async reset(): Promise<void> {
    this.verificationKey = null;
    this.healthy = true;
  }

  /**
   * Generate a proof.
   *
   * @param input Private witnesses and public inputs.
   * @throws If witness generation or proving fails.
   */
  async generateProof(input: ProofInput): Promise<ProofOutput> {
    const snarkjs = await loadSnarkjs();
    const signals = toCircuitSignals(input);

    try {
      const { proof, publicSignals } = await snarkjs.groth16.fullProve(
        signals,
        this.artifacts.wasmPath,
        this.artifacts.zkeyPath,
      );

      return {
        proof,
        publicSignals,
        // Circom emits declared outputs before public inputs.
        nullifier: BigInt(publicSignals[0]!),
        share: BigInt(publicSignals[1]!),
        epoch: input.epoch,
        messageIndex: input.messageIndex,
      };
    } catch (error) {
      this.healthy = false;
      throw error;
    }
  }

  /**
   * Verify a proof against the circuit's verification key.
   *
   * @returns False for an invalid proof; never throws on bad input.
   */
  async verifyProof(
    proof: unknown,
    publicSignals: readonly string[],
  ): Promise<boolean> {
    try {
      const snarkjs = await loadSnarkjs();
      const key = await this.loadVerificationKey();

      return await snarkjs.groth16.verify(key, publicSignals as string[], proof);
    } catch {
      // A malformed proof is a rejection, not a prover fault.
      return false;
    }
  }

  private async loadVerificationKey(): Promise<unknown> {
    if (this.verificationKey) return this.verificationKey;

    const raw = await readFile(this.artifacts.verificationKeyPath, 'utf8');
    this.verificationKey = JSON.parse(raw);

    return this.verificationKey;
  }
}

/** Minimal shape of the snarkjs groth16 surface we depend on. */
interface SnarkjsModule {
  groth16: {
    fullProve(
      input: Record<string, unknown>,
      wasmPath: string,
      zkeyPath: string,
    ): Promise<{ proof: unknown; publicSignals: string[] }>;
    verify(
      vkey: unknown,
      publicSignals: string[],
      proof: unknown,
    ): Promise<boolean>;
  };
}

/**
 * Load snarkjs lazily.
 *
 * It is a heavy dependency and only needed once proving actually
 * happens, so importing it at module scope would tax every consumer of
 * the SDK — including those that never generate a proof.
 */
async function loadSnarkjs(): Promise<SnarkjsModule> {
  return (await import('snarkjs')) as unknown as SnarkjsModule;
}
